import Navbar from './components/Navbar.jsx'
import Hero from './components/Hero.jsx'
import EmotionalIntro from './components/EmotionalIntro.jsx'
import HowItWorks from './components/HowItWorks.jsx'
import BirthdayStory from './components/BirthdayStory.jsx'
import WeddingStory from './components/WeddingStory.jsx'
import Celebrations from './components/Celebrations.jsx'
import WhyYourThoughts from './components/WhyYourThoughts.jsx'
import Pricing from './components/Pricing.jsx'
import AdditionalPricing from './components/AdditionalPricing.jsx'
import OrderProcess from './components/OrderProcess.jsx'
import ChangePolicy from './components/ChangePolicy.jsx'
import OurStory from './components/OurStory.jsx'
import AdvertisementVideo from './components/AdvertisementVideo.jsx'
import MemoryGallery from './components/MemoryGallery.jsx'
import CTA from './components/CTA.jsx'
import Contact from './components/Contact.jsx'
import Footer from './components/Footer.jsx'
import FloatingWhatsApp from './components/FloatingWhatsApp.jsx'

export default function App(){return <div className="min-h-screen bg-cocoa-950"><Navbar/><main><Hero/><EmotionalIntro/><HowItWorks/><BirthdayStory/><WeddingStory/><Celebrations/><WhyYourThoughts/><Pricing/><AdditionalPricing/><OrderProcess/><ChangePolicy/><OurStory/><AdvertisementVideo/><MemoryGallery/><CTA/><Contact/></main><Footer/><FloatingWhatsApp/></div>}
